# Simple Neural Nework
here we try to write a simple neural network to understand what backpropagation really do :)
## Now we create a simple one layer newtork 

### continue our feedforward network and make it a complete neural network that can predict

In [2]:
import numpy as np
#activation funcion
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)
#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2) 
        self.weights2   = np.random.rand(2,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)
    #feedforward function 
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, ((self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot((self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    
    nn = NeuralNetwork(X,y)

    for i in range(100):
        nn.feedforward()
        nn.backprop()

    print(nn.y - nn.output)



[[-0.49871682]
 [ 0.49816503]
 [ 0.49807871]
 [-0.50393413]]


# Python Useful Libraries
Simple Example!

In [3]:
from sklearn.neural_network import MLPClassifier
X = [[0, 0], [1, 1]]
y = [[0], [1]]
clf = MLPClassifier()
clf.fit(X, y)                         



/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

## OR Function
Let us start with a simple example of Boolean OR

In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[]
y_training=[]



In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)  
mlp.predict([[1,1]])



/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

### Practice: Bipolar OR

Instead of {0, 1}, we can also change the value into bipolar {-1, +1}. Try the following OR gate using Perceptron and MLP.

In [6]:


X_training=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_training=[1, 
            1,
            1,
            -1
           ]
X_testing=X_training
y_true=y_training


## Multi-Layer Networks

The following code is the example of how you will use Multi-Layer Perceptron (MLP) Neural Network to train, predict. You can also get the weights of the Neural Network.


In [7]:

mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_training)                      # prediction
print(y_pred)                                      # show the output
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
print(mlp.coefs_)                                 # synapsis weights



[ 1  1  1 -1]
[(2, 100), (100, 1)]
[array([[  6.14603341e-02,  -2.51583354e-01,  -1.46354990e-01,
         -2.19938647e-01,   3.26618223e-01,   8.69601956e-02,
         -3.76685393e-01,  -2.71250534e-07,   1.20344529e-01,
         -2.08239510e-01,   3.52211333e-01,   1.10191954e-01,
          3.21321486e-01,  -2.65230947e-01,  -2.52099239e-01,
          2.91153365e-02,  -1.15878877e-01,   2.16764398e-01,
         -2.88468863e-01,  -8.39704621e-02,   2.86131635e-01,
          4.86089767e-04,   1.31270576e-01,   1.24665085e-01,
          7.03918430e-03,   3.14437546e-01,   2.13004634e-01,
          2.79956143e-02,  -2.01160844e-01,  -1.79971953e-01,
         -1.51477684e-01,  -2.75324702e-01,  -3.96094505e-01,
          1.08311004e-01,  -5.07592307e-03,   1.88208536e-01,
          3.61828082e-01,  -5.35197411e-04,   2.51387775e-02,
          1.08018688e-01,   1.85701711e-02,  -3.28611149e-01,
          1.31148478e-01,  -1.51211201e-01,   1.29547788e-01,
          3.86493859e-01,  -5.4350

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Now your Turn!
### Experiments

-  Change the data (X_training, y_training, X_testing)
-  Change the hidden layer of MLP: number of layers (int) or size (n,m)
-  Change activation function of MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'




In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
X_testing = X_training
y_true = y_training

In [9]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100,300 ), activation='logistic') # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)                      # prediction
print(y_pred)                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights



[1 1 1 1]
acuracy= 0.75
[(2, 200), (200, 100), (100, 300), (300, 1)]


4

### XNOR 
Try solve the following Boolean Exclusive Not Or (XNOR) problem. How to improve the accuracy? How many minimum hidden layer is needed to make it 100% accuracy

In [10]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            0,
            0,
            0
           ]
X_testing=X_training
y_true=y_training
mlp = MLPClassifier(hidden_layer_sizes=(50)) # set the method
mlp.fit(X_training, y_training)                    # training
                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights


acuracy= 0.25
[(2, 50), (50, 1)]


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


2

## Data from File

In [11]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.94666666666666666

### Your Turn
Creat your network based on only two features of the given dataset.

In [12]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.94666666666666666

Try to create and train a nerural network for a given dataset with higher accuracy!

In [13]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.98666666666666669