# Simple Neural Nework
here we try to write a simple neural network to understand what backpropagation really do :)
## Now we create a simple one layer newtork 

### continue our feedforward network and make it a complete neural network that can predict

In [159]:
import numpy as np

In [160]:
#activation funcion
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

#derivative of activation funcion
def sigmoid_derivative(x):
    return x * (1.0 - x)
    #return sigmoid(x) * (1.0 - sigmoid(x)) #laut Folien ist das die Formel

#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2)
        self.weights2   = np.random.rand(2,1)          
        self.y          = y
        self.output     = np.zeros(self.y.shape)
    #feedfarward function 
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the Error with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, ((self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot((self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
   
    nn = NeuralNetwork(X, y) # make instance of your NerualNetwork class
   
    #do the iteration for learning
    for i in range(100):
        nn.feedforward()
        nn.backprop()
        
    print(nn.y - nn.output)
    print(nn.y)
    print(nn.output)



[[-0.4946683 ]
 [ 0.48067154]
 [ 0.50842225]
 [-0.50655747]]
[[0]
 [1]
 [1]
 [0]]
[[ 0.4946683 ]
 [ 0.51932846]
 [ 0.49157775]
 [ 0.50655747]]


In [161]:
X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
y = np.array([[0],[1],[1],[0]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [162]:
weights1   = np.random.rand(X.shape[1],2)
weights1

array([[ 0.18800682,  0.6602511 ],
       [ 0.19546521,  0.63628758],
       [ 0.65732607,  0.70565005]])

In [163]:
np.dot(X, weights1)

array([[ 0.65732607,  0.70565005],
       [ 0.85279128,  1.34193763],
       [ 0.84533289,  1.36590115],
       [ 1.0407981 ,  2.00218873]])

# Python Useful Libraries
Simple Example!

In [164]:
from sklearn.neural_network import MLPClassifier
X = [[0, 0], [1, 1]]
y = [[0], [1]]
clf = MLPClassifier()
clf.fit(X, y)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [165]:
print(clf.predict([[1, 2]]))
print(clf.predict([[0, 0]]))
print(clf.predict([[1, 1]]))
print(clf.predict([[0, 2]]))

[1]
[0]
[1]
[1]


## OR Function
Let us start with a simple example of Boolean OR

In [166]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[]
y_training=[]



In [167]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)  

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [168]:
print(mlp.predict([[0,0]]))
print(mlp.predict([[0,1]]))
print(mlp.predict([[1,0]]))
print(mlp.predict([[1,1]]))

[0]
[1]
[1]
[1]


### Practice: Bipolar OR

Instead of {0, 1}, we can also change the value into bipolar {-1, +1}. Try the following OR gate using Perceptron and MLP.

In [169]:
X_training=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_training=[1, 
            1,
            1,
            -1
           ]
X_testing=X_training
y_true=y_training

mlp_bipolar = MLPClassifier() # set the method
mlp_bipolar.fit(X_testing, y_true)  

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [170]:
print(mlp_bipolar.predict([[-1,-1]]))
print(mlp_bipolar.predict([[-1,1]]))
print(mlp_bipolar.predict([[1,-1]]))
print(mlp_bipolar.predict([[1,1]]))

[-1]
[1]
[1]
[1]


## Multi-Layer Networks

The following code is the example of how you will use Multi-Layer Perceptron (MLP) Neural Network to train, predict. You can also get the weights of the Neural Network.


In [171]:

mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_training)                      # prediction
print(y_pred)                                      # show the output
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
print(mlp.coefs_)                                 # synapsis weights



[ 1  1  1 -1]
[(2, 100), (100, 1)]
[array([[ -3.22822008e-01,   1.20305555e-02,   1.17372650e-02,
          1.20601169e-01,   2.68552268e-01,  -4.47320236e-03,
         -3.18317541e-01,  -2.28098078e-06,  -3.49666255e-01,
          2.81863053e-01,   1.16775119e-01,   3.48459140e-01,
          1.66627409e-06,  -3.24137001e-01,  -4.32288629e-06,
         -3.44608013e-01,  -2.56885499e-01,   1.66877938e-01,
          2.13712192e-01,   4.22646806e-01,   5.49503530e-08,
          3.13876901e-02,   1.94767681e-01,  -1.69470911e-01,
         -2.80068872e-02,  -8.52902785e-02,  -1.06174363e-01,
         -3.13852587e-01,   2.21425352e-01,   1.83824759e-01,
          3.13288598e-01,   1.13580632e-01,  -4.78991125e-02,
          4.32703936e-01,  -3.34498694e-02,  -1.36247328e-01,
          3.80892361e-01,  -1.08533972e-01,  -2.99841271e-02,
          2.32771676e-01,  -1.67115211e-01,  -5.00496749e-02,
          1.90930461e-01,   2.14841599e-02,  -2.70999173e-03,
         -2.98719164e-01,  -1.2574

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Now your Turn!
### Experiments

-  Change the data (X_training, y_training, X_testing)
-  Change the hidden layer of MLP: number of layers (int) or size (n,m)
-  Change activation function of MLP: {'identity', 'logistic',...}




In [172]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]

X_testing = X_training
y_true = y_training

In [173]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100,300), activation='logistic') # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)                      # prediction
print(y_pred)                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=', accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_) 

# 2 neurons auf 200 auf 100 auf 300 auf 1

[1 1 1 1]
acuracy= 0.75
[(2, 200), (200, 100), (100, 300), (300, 1)]


4

### XNOR 
Try solve the following Boolean Exclusive Not Or (XNOR) problem. How to improve the accuracy? How many minimum hidden layer is needed to make it 100% accuracy

In [174]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[0, 
            0,
            0,
            1
           ]
X_testing=X_training
y_true=y_training    

In [175]:
mlp = MLPClassifier(hidden_layer_sizes=(50)) # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)
                                      # show the output
print(np.array(y_true).flatten())
print(np.array(y_pred).flatten())
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights

[0 0 0 1]
[0 0 0 0]
acuracy= 0.75
[(2, 50), (50, 1)]


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


2

## Data from File

In [176]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

train = pd.read_csv("iris.csv")
train=pd.get_dummies(train)
features = train.columns[:-1]
y = train.columns[-1]
Y =(train[y])
X = train[features]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
nn.fit(X_train,y_train)
nn.score(X_test,y_test)


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


1.0

### Your Turn
Creat your network based on only two features of the given dataset.

In [177]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.97333333333333338

Try to create and train a nerural network for a given dataset with higher accuracy!

In [178]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.70666666666666667