# Simple Neural Nework
here we try to write a simple neural network to understand what backpropagation really do :)
## Now we create a simple one layer newtork 

### continue our feedforward network and make it a complete neural network that can predict

In [236]:
import numpy as np

In [237]:
#activation funcion
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

#derivative of activation funcion
def sigmoid_derivative(x):
    return x * (1.0 - x)
    #return sigmoid(x) * (1.0 - sigmoid(x)) #laut Folien ist das die Formel

#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2)
        self.weights2   = np.random.rand(2,1)          
        self.y          = y
        self.output     = np.zeros(self.y.shape)
    #feedfarward function 
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the Error with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, ((self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot((self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
   
    nn = NeuralNetwork(X, y) # make instance of your NerualNetwork class
   
    #do the iteration for learning
    for i in range(100):
        nn.feedforward()
        nn.backprop()
        
    print(nn.y - nn.output)
    print(nn.y)
    print(nn.output)



[[-0.50094421]
 [ 0.49639754]
 [ 0.48625802]
 [-0.50998644]]
[[0]
 [1]
 [1]
 [0]]
[[ 0.50094421]
 [ 0.50360246]
 [ 0.51374198]
 [ 0.50998644]]


In [238]:
X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
y = np.array([[0],[1],[1],[0]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [239]:
weights1   = np.random.rand(X.shape[1],2)
weights1

array([[ 0.62280303,  0.82768106],
       [ 0.41043887,  0.80316101],
       [ 0.07218135,  0.09321666]])

In [240]:
np.dot(X, weights1)

array([[ 0.07218135,  0.09321666],
       [ 0.48262022,  0.89637767],
       [ 0.69498438,  0.92089771],
       [ 1.10542325,  1.72405872]])

# Python Useful Libraries
Simple Example!

In [241]:
from sklearn.neural_network import MLPClassifier
X = [[0, 0], [1, 1]]
y = [[0], [1]]
clf = MLPClassifier()
clf.fit(X, y)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [242]:
print(clf.predict([[1, 2]]))
print(clf.predict([[0, 0]]))
print(clf.predict([[1, 1]]))
print(clf.predict([[0, 2]]))

[1]
[0]
[1]
[1]


## OR Function
Let us start with a simple example of Boolean OR

In [243]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[]
y_training=[]



In [244]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)  

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [245]:
print(mlp.predict([[0,0]]))
print(mlp.predict([[0,1]]))
print(mlp.predict([[1,0]]))
print(mlp.predict([[1,1]]))

[0]
[1]
[1]
[1]


### Practice: Bipolar OR

Instead of {0, 1}, we can also change the value into bipolar {-1, +1}. Try the following OR gate using Perceptron and MLP.

In [246]:
X_training=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_training=[1, 
            1,
            1,
            -1
           ]
X_testing=X_training
y_true=y_training

mlp_bipolar = MLPClassifier() # set the method
mlp_bipolar.fit(X_testing, y_true)  

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [247]:
print(mlp_bipolar.predict([[-1,-1]]))
print(mlp_bipolar.predict([[-1,1]]))
print(mlp_bipolar.predict([[1,-1]]))
print(mlp_bipolar.predict([[1,1]]))

[-1]
[1]
[1]
[1]


## Multi-Layer Networks

The following code is the example of how you will use Multi-Layer Perceptron (MLP) Neural Network to train, predict. You can also get the weights of the Neural Network.


In [248]:

mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_training)                      # prediction
print(y_pred)                                      # show the output
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
print(mlp.coefs_)                                 # synapsis weights



[ 1  1  1 -1]
[(2, 100), (100, 1)]
[array([[  2.35757334e-01,  -8.97010834e-08,   9.12256896e-02,
         -1.13559796e-01,   3.62386552e-01,  -4.84050692e-02,
          1.78576540e-02,   1.48151180e-01,   1.46341184e-01,
         -2.96656228e-02,   6.01060462e-02,  -5.69960004e-03,
         -1.93370682e-01,  -8.40378550e-02,  -2.41938825e-01,
         -2.50806976e-01,   1.90432286e-01,  -3.41069149e-01,
          5.02273255e-02,   2.25970409e-01,   1.40400742e-01,
         -5.88745125e-02,  -5.05880767e-02,  -1.21142813e-01,
         -1.19552891e-01,   1.60787323e-01,  -1.82672984e-01,
         -1.07292621e-01,  -9.03739002e-09,  -6.21365265e-02,
         -5.44931870e-08,   2.28960802e-01,  -1.65419275e-01,
          3.53959884e-01,   2.70069269e-01,  -7.07954298e-02,
         -1.36672060e-01,   7.24479829e-03,   9.68212052e-06,
         -3.36610733e-01,   1.85994009e-01,   4.79233284e-01,
         -1.08987340e-01,   4.02289892e-01,   1.49630633e-01,
          2.90188530e-01,  -2.1571

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Now your Turn!
### Experiments

-  Change the data (X_training, y_training, X_testing)
-  Change the hidden layer of MLP: number of layers (int) or size (n,m)
-  Change activation function of MLP: {'identity', 'logistic',...}




In [249]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]

X_testing = X_training
y_true = y_training

In [250]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100,300), activation='logistic') # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)                      # prediction
print(y_pred)                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=', accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_) 

[1 1 1 1]
acuracy= 0.75
[(2, 200), (200, 100), (100, 300), (300, 1)]


4

### XNOR 
Try solve the following Boolean Exclusive Not Or (XNOR) problem. How to improve the accuracy? How many minimum hidden layer is needed to make it 100% accuracy

In [251]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            0,
            0,
            0
           ]
X_testing=X_training
y_true=y_training    

In [252]:
mlp = MLPClassifier(hidden_layer_sizes=(50)) # set the method
mlp.fit(X_training, y_training)                    # training
                                      # show the output
print(np.array(y_true).flatten())
print(np.array(y_pred).flatten())
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights

[1 0 0 0]
[1 1 1 1]
acuracy= 0.25
[(2, 50), (50, 1)]


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


2

## Data from File

In [253]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

train = pd.read_csv("iris.csv")
train=pd.get_dummies(train)
features = train.columns[:-1]
y = train.columns[-1]
Y =(train[y])
X = train[features]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
nn.fit(X_train,y_train)
nn.score(X_test,y_test)


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


1.0

### Your Turn
Creat your network based on only two features of the given dataset.

In [254]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.98666666666666669

Try to create and train a nerural network for a given dataset with higher accuracy!

In [255]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.97333333333333338