# Simple Neural Nework
here we try to write a simple neural network to understand what backpropagation really do :)
## Now we create a simple one layer newtork 

### continue our feedforward network and make it a complete neural network that can predict

In [9]:
import numpy as np

#activation funcion

#deivative of activation funcion

#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = 
        self.weights1   = 
        self.weights2   =                  
        self.y          = 
        self.output     = 
    #feedfarward function 
    def feedforward(self):
        self.layer1 = 
        self.output = 
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the Error with respect to weights2 and weights1
        d_weights2 = 
        d_weights1 =

        # update the weights with the derivative (slope) of the loss function
        self.weights1 = 
        self.weights2 =

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
   
    nn = # make instance of your NerualNetwork class
   
    #do the iteration for learning
   
    print()



SyntaxError: invalid syntax (<ipython-input-9-c75ce557c583>, line 12)

In [10]:
import numpy as np
#activation funcion
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)
#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2) 
        self.weights2   = np.random.rand(2,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)
    #feedforward function 
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, ((self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot((self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    
    nn = NeuralNetwork(X,y)

    for i in range(100):
        nn.feedforward()
        nn.backprop()

    print(nn.y - nn.output)



[[-0.50000023]
 [ 0.49770154]
 [ 0.49959911]
 [-0.50244279]]


# Python Useful Libraries
Simple Example!

In [11]:
from sklearn.neural_network import MLPClassifier
X = [[0, 0], [1, 1]]
y = [[0], [1]]
clf = MLPClassifier()
clf.fit(X, y)                         



/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

## OR Function
Let us start with a simple example of Boolean OR

In [12]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[]
y_training=[]



In [13]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)  
mlp.predict([[1,1]])



/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

### Practice: Bipolar OR

Instead of {0, 1}, we can also change the value into bipolar {-1, +1}. Try the following OR gate using Perceptron and MLP.

In [14]:


X_training=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_training=[1, 
            1,
            1,
            -1
           ]
X_testing=X_training
y_true=y_training


## Multi-Layer Networks

The following code is the example of how you will use Multi-Layer Perceptron (MLP) Neural Network to train, predict. You can also get the weights of the Neural Network.


In [15]:

mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_training)                      # prediction
print(y_pred)                                      # show the output
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
print(mlp.coefs_)                                 # synapsis weights



[ 1  1  1 -1]
[(2, 100), (100, 1)]
[array([[ -5.48874571e-04,  -2.60865763e-01,   3.52015583e-02,
          1.61367017e-03,  -3.09758919e-01,   1.83033526e-01,
         -1.60446667e-01,   3.15868426e-01,  -2.83613853e-01,
          7.24446253e-03,  -2.65435660e-01,   3.42878671e-02,
          1.20573354e-01,   3.03794826e-01,  -2.64908795e-01,
         -1.21845727e-01,   1.24294285e-01,  -2.60246785e-03,
          1.69120247e-01,  -2.84134069e-01,  -1.77556633e-01,
          1.47449704e-01,   7.88717376e-02,   2.80090092e-01,
         -3.42853280e-08,   2.95966442e-01,  -1.07798550e-01,
          1.17437344e-01,   2.89456981e-01,  -1.17301316e-01,
         -5.20660684e-02,  -7.85846565e-02,  -8.07425924e-02,
         -1.18319375e-01,   1.84028313e-02,   3.23279073e-01,
          4.22065302e-02,   3.83576275e-01,  -7.18640814e-03,
         -2.72531796e-01,  -2.09909869e-01,  -6.18343740e-03,
         -2.38224543e-01,   1.06873887e-01,  -1.02253317e-01,
         -3.05599047e-01,  -1.6280

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Now your Turn!
### Experiments

-  Change the data (X_training, y_training, X_testing)
-  Change the hidden layer of MLP: number of layers (int) or size (n,m)
-  Change activation function of MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'




In [16]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
X_testing = X_training
y_true = y_training

In [17]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100,300 ), activation='logistic') # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)                      # prediction
print(y_pred)                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights



[1 1 1 1]
acuracy= 0.75
[(2, 200), (200, 100), (100, 300), (300, 1)]


4

### XNOR 
Try solve the following Boolean Exclusive Not Or (XNOR) problem. How to improve the accuracy? How many minimum hidden layer is needed to make it 100% accuracy

In [23]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            0,
            0,
            0
           ]
X_testing=X_training
y_true=y_training
mlp = MLPClassifier(hidden_layer_sizes=(50)) # set the method
mlp.fit(X_training, y_training)                    # training
                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights


acuracy= 0.25
[(2, 50), (50, 1)]


/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


2

## Data from File

In [19]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

/home/philipp/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.95999999999999996

### Your Turn
Creat your network based on only two features of the given dataset.

In [20]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv(r"C:\Users\mahsa\Desktop\iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

FileNotFoundError: File b'C:\\Users\\mahsa\\Desktop\\iris.csv' does not exist

Try to create and train a nerural network for a given dataset with higher accuracy!

In [ ]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv(r"C:\Users\mahsa\Desktop\iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)