In [1]:
import numpy as np


In [2]:
one_dim=np.array([1,2,3])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
two_dim=np.array([[1,2,3],
                 [4,5,6]])

In [5]:
two_dim.ndim

2

In [6]:
one_dim.dtype

dtype('int64')

In [7]:
two_dim.size

6

In [8]:
two_dim.shape

(2, 3)

In [9]:
two_dim[:,1]

array([2, 5])

In [10]:
two_dim[np.newaxis]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [11]:
two_dim[np.newaxis].shape

(1, 2, 3)

In [12]:
two_dim[...,np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [13]:
np.reshape(two_dim, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
a=np.random.random((2,3))

In [19]:
print(a
     )

[[0.03184819 0.1860782  0.81064335]
 [0.680508   0.16189323 0.63640001]]


In [20]:
a.max()

0.8106433463225076

In [21]:
a.sum(axis=0)

array([0.71235619, 0.34797143, 1.44704336])

In [22]:
a+3

array([[3.03184819, 3.1860782 , 3.81064335],
       [3.680508  , 3.16189323, 3.63640001]])

In [23]:
a*3

array([[0.09554456, 0.55823461, 2.43193004],
       [2.04152401, 0.48567968, 1.90920003]])

In [24]:
b=np.ones((2,3))*3

In [25]:
a*b

array([[0.09554456, 0.55823461, 2.43193004],
       [2.04152401, 0.48567968, 1.90920003]])

In [26]:
a.dot(b.T)

array([[3.08570921, 3.08570921],
       [4.43640373, 4.43640373]])

In [27]:
np.stack((one_dim,one_dim),axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [28]:
np.concatenate((one_dim,one_dim))

array([1, 2, 3, 1, 2, 3])

In [29]:
np.concatenate(([one_dim],[one_dim]))

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
a[:]

array([[0.03184819, 0.1860782 , 0.81064335],
       [0.680508  , 0.16189323, 0.63640001]])

In [31]:
a[1,1]

0.16189322780582982

In [32]:
a[2:,:]

array([], shape=(0, 3), dtype=float64)

In [33]:
a[1:]

array([[0.680508  , 0.16189323, 0.63640001]])

In [34]:
a=np.random.random((5,5,5))

In [35]:
a[2:,1,:]

array([[0.38743946, 0.97863215, 0.033392  , 0.17273867, 0.82051774],
       [0.55116697, 0.95331697, 0.3763203 , 0.60650716, 0.0556516 ],
       [0.96508388, 0.27095358, 0.56089856, 0.83377828, 0.66958095]])