## A Simple Feedforward Neural Network
We simply try to see how the feedforward neural networks work in practice! 
-  Our Neural Network has one hidden layer and two inputs
-  With two inputs and one hidden layer with two neurons, how many number of weights do we need? 6

In [1]:
import numpy as np

In [64]:
#activation funcion
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x #set of training input
        #randomly assign the weights
        self.weights1   = np.random.rand(self.input.shape[1],2) #create ? random weights for
        self.weights2   = np.random.rand(2,1) #create ? random weights       
        self.y          = y #set of output for the training input set
        self.output     = np.zeros(self.y.shape) #add value of zero at first at the shape of y
    
    #feedfarward function 
    def feedforward(self):
        #do calculation for the input value of neurons in the hidden layer
        in_hidden_node1 = np.dot(X, weights1[0])
        print('### in_hidden_node1 ###')
        print(in_hidden_node1)
        in_hidden_node2 = np.dot(X, weights1[1])
        print('### in_hidden_node2 ###')
        print(in_hidden_node2)
        #activation function and calculate the value of layer one and output of your network
        self.layer1n1 = sigmoid(in_hidden_node1)
        print('### layer1n1 ###')
        print(self.layer1n1)
        self.layer1n2 = sigmoid(in_hidden_node2)
        print('### layer1n2 ###')
        print(self.layer1n2)
        self.output = sigmoid(in_hidden_node1 * weights2[0] + in_hidden_node2 * weights2[1])
        return self.output #output
#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)
    # print your output layer and your weights
    nn.feedforward()
    print('############# output #################')
    print(nn.output)
    print('### weights1 ###')
    print(nn.weights1)
    print('### weights2 ###')
    print(nn.weights2)

### in_hidden_node1 ###
[ 0.          0.93741031  0.01689647  0.95430678]
### in_hidden_node2 ###
[ 0.          0.90632003  0.03852161  0.94484164]
### layer1n1 ###
[ 0.5         0.71857626  0.50422402  0.72198048]
### layer1n2 ###
[ 0.5         0.71224654  0.50962921  0.72007661]
############# output #################
[ 0.5         0.76289635  0.51033716  0.7702953 ]
### weights1 ###
[[ 0.00903544  0.78568969]
 [ 0.60515657  0.36219116]]
### weights2 ###
[[ 0.14738943]
 [ 0.79132872]]
